services:
  users-service:
    build: .
    container_name: users-service
    expose:
      - "4000"
    networks:
      - my-microservices-net
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
    env_file:
      - .env

networks:
  my-microservices-net:
    external: true
